#pragma once

#define CAFE_OS_SDK_BUILD_VERSION ""
#define CAFE_OS_SDK_VERSION_STRING ""
#define CAFE_OS_SDK_VERSION 10700
#define CAFE_OS_SDK_VERSION_MAJOR 1
#define CAFE_OS_SDK_VERSION_MINOR 7
#define CAFE_OS_SDK_VERSION_PATCH 0